Repository GV14982/async-airtable, pull requests merged in 2020-10, with the labels that each got.

#2 ♻ Basically completely rewrote this to remove the airtablejs library.
  lib/asyncAirtable.js
  package-lock.json
  package.json
Labels: hacktoberfest-accepted

#15 Change method names
  .eslintrc.json
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/testLinux.yml
  .github/workflows/testMac.yml
  .github/workflows/testWindows.yml
  .gitignore
  .npmignore
  .prettierrc.json
  .sample.env
  LICENSE.md
  README.md
  jsconfig.json
  lib/asyncAirtable.js
  package-lock.json
  package.json
  setupFile.js
  tests/bulkCreate.test.js
  tests/bulkDelete.test.js
  tests/bulkUpdate.test.js
  tests/createRecord.test.js
  tests/deleteRecord.test.js
  tests/find.test.js
  tests/main.test.js
  tests/select.test.js
  tests/updateRecord.test.js
Labels: hacktoberfest-accepted

#13 ✨ Adds "Destructive Update" support
  .github/workflows/testLinux.yml
  .github/workflows/testMac.yml
  .github/workflows/testWindows.yml
  .gitignore
  .sample.env
  jest.config.js
  lib/asyncAirtable.js
  package-lock.json
  package.json
  tests/bulkCreate.test.js
  tests/bulkDelete.test.js
  tests/bulkUpdate.test.js
  tests/createRecord.test.js
  tests/deleteRecord.test.js
  tests/destructiveUpdateRecord.test.js
Labels: hacktoberfest-accepted

#18 📝 Adds more documentation.
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  package.json
Labels: documentation, hacktoberfest-accepted

#23 📝 Adds JSDoc and documentation
  .assets/logo_black.png
  .assets/logo_white.png
  .gitignore
  .npmignore
  LICENSE.md
  README.md
  jsdoc.conf.json
  lib/asyncAirtable.js
  package-lock.json
  package.json
Labels: documentation

#26 📝 Added additional typedefs to docs and return types
  README.md
  lib/asyncAirtable.js
Labels: documentation
